### Partner
POST http://localhost:8080/partners
Content-Type: application/json

{
    "name": "Partner 3"
}

### Event
POST localhost:8080/events/4c705208-091b-43ae-8619-c11c1a7ebcee
Content-Type: application/json

{
  "eventName": "Hell Fest",
  "eventDescription": "Hell Fest",
  "date": "2024-01-07T00:00:00"
}