version: '3.9'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=ddd
      - POSTGRES_USER=ddd
      - POSTGRES_DB=ddd
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql